version: "3.8"

services:

  php-fpm:

    image: webdevops/php-nginx:7.4

    container_name: sendMail_webapp

    working_dir: /app

    volumes:

      - ./:/app

    environment:

      - WEB_DOCUMENT_ROOT=/app/webroot

    ports:

      - "8082:80"